export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  SUPPORT = 'SUPPORT',
  CLIENT = 'CLIENT',
  AFFILIATE = 'AFFILIATE',
  EDITOR = 'EDITOR',
}
