-- SkillGod — auto-generated by sg init
-- Source from init.lua: require('.nvim.skillgod')

local skillgod_prompt = [[SkillGod is active. 1,920 curated skills and project memory.
Core rules: verify output before saying done; validate inputs before DB writes;
never silently ignore errors. Run: sg find <task> | sg remember "<decision>" | sg timeline]]

-- Avante.nvim
if pcall(require, 'avante') then
  require('avante').setup({ system_prompt = skillgod_prompt })
end

-- CopilotChat.nvim
if pcall(require, 'CopilotChat') then
  require('CopilotChat').setup({ system_prompt = skillgod_prompt })
end

return { prompt = skillgod_prompt }
